### PR TITLE
Add setUrl method.

### PR DESCRIPTION
**Pull request by lnkpaulo**
_setUrl(url)_ method implemented to support dynamic _url_ changes.

### CODE REVIEW

**Comment by perliedman** [comment]
Looking good except for a small detail I commented. Can you fix that, and I think we're good to merge?

**Comment by lnkpaulo** [comment]
Yes it is more clean. I will fix it.

**Comment by lnkpaulo** [comment]
Hi,

It is only to say I'm using the set Url without issues. There is a small improvement which can be implemented. When the url is setted the change will be only visible in the map when the timer cycle is restarting.

**Comment by perliedman** [comment]
Good point! You could add a call to `this.update()` after setting the URL to fix this.

**Pull request merged**
